# Generated by Django 4.2 on 2023-05-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='journal',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='penname',
            field=models.CharField(max_length=20),
        ),
    ]
